name: "pds-grupo-a8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    platform: linux/amd64
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    platform: linux/amd64
    depends_on:
      - zookeeper
    ports:
      - 29092:9092
      - 19092:19092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092,CONNECTIONS_FROM_HOST://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # -- Database --
  productdb:
    image: postgres
    platform: linux/amd64
    restart: always
    ports:
      - 54320:5432
    environment:
      POSTGRES_USER: product
      POSTGRES_PASSWORD: product

  userdb:
    image: postgres
    platform: linux/amd64
    restart: always
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user

  digitaldb:
    image: postgres
    platform: linux/amd64
    restart: always
    ports:
      - 54322:5432
    environment:
      POSTGRES_USER: digital
      POSTGRES_PASSWORD: digital

  # -- Backend --
  product-solution:
    image: registry.gitlab.com/uoc/pdp-pds/pdp_pds_2025_2026/pds_2025_2026_a8/photo-and-film-4-you/product-solution:v1.3.1
    depends_on:
      - productdb
      - kafka
    ports:
      - "18081:18081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://productdb:5432/product
      SPRING_DATASOURCE_USERNAME: product
      SPRING_DATASOURCE_PASSWORD: product
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  user-solution:
    image: registry.gitlab.com/uoc/pdp-pds/pdp_pds_2025_2026/pds_2025_2026_a8/photo-and-film-4-you/user-solution:v1.2.4
    depends_on:
      - userdb
      - kafka
      - product-solution
    ports:
      - "18082:18082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://userdb:5432/user
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      PRODUCTSERVICE_GETPRODUCTDETAILS_URL: http://product-solution:18081/products/{productId}

  # -- Frontend --
  frontend:
    image: registry.gitlab.com/uoc/pdp-pds/pdp_pds_2025_2026/pds_2025_2026_a8/photo-and-film-4-you/frontend-solution:v2.0.0
    depends_on:
      - product-solution
    ports:
      - "80:80"

  # -- Tools --
  adminer:
    image: adminer
    platform: linux/amd64
    restart: always
    ports:
      - 18080:8080
